#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit ${1}
branch="$(git rev-parse --abbrev-ref HEAD | sed 's/^origin\///')" 
commitMsgFile=$1
msg=$(cat "$commitMsgFile")
echo "$branch: $msg" > "$commitMsgFile"
